### ISSUE TITLE
No way to provide your own swagger.json in 3.0.17

### ISSUE THREAD

**Issue by jetmind** [metosin/ring-swagger-ui#11]
Is this change intentional? https://github.com/metosin/ring-swagger-ui/commit/b04bd6bd7459fc9312ae803c1ba4eab668d5de11#diff-619237f325d52e3ec16296762beb7325L76

```diff
-    url: API_CONF.url,
+    url: "http://petstore.swagger.io/v2/swagger.json",
```

Seems like there's no way to override this. I've tried providing `config.json` but it had no effect.

I'm not quite sure what to put in `config.json` but have tried this:

```
{"url": "/api/docs.json"}
```

**Comment by Deraen** [comment]
There is no `API_CONF` anymore. `url` in `config.json` should work: https://github.com/metosin/ring-swagger/pull/123/files.

**Comment by jetmind** [comment]
Actually, this works. It was just a silly mistake on my side: forgot to set content-type on the `config.json` response. Thanks!
