### ISSUE TITLE
Is there a way to disable swagger UI on certain environments?

### ISSUE THREAD

**Issue by cksharma11** [metosin/ring-swagger-ui#18]
Hi, I want to disable swagger UI on PROD environment for some reasons, I was looking if I can do this in Clojure, but I didn't find anything.

There is something called Profiles in Spring, I'm wondering if we have something similar here?

**Comment by Deraen** [comment]
On Reitit, you can just check something (env variable, system property, config from a file, whatever) if the swagger routes should be included in the route tree: https://cljdoc.org/d/metosin/reitit/0.5.12/doc/ring/swagger-support#simple-example so `(when something ["/swagger" ...])` around the swagger routes.

Something similar is possible with Compojure-api, though the route tree has to be functions so it is not as obvious. I don't remember what the Swagger handlers look like on Compojure-API, but generally if you ensure you return nil handler you can conditionally disable a handler:

`(routes (if enable-swager (swagger-routes ...) (constantly nil)))`. (https://github.com/metosin/compojure-api/blob/master/src/compojure/api/swagger.clj#L56)

Or if you use Compojure-API `api` `:swagger` option, I think you can just set it to `nil` to disable swagger json and UI (or the default is nil and disabled?): https://github.com/metosin/compojure-api/blob/master/examples/simple/src/example/handler.clj#L15-L20
