### ISSUE TITLE
Update to Swagger UI v4.5.0

### ISSUE THREAD

**Issue by pedrocicoleme** [metosin/ring-swagger-ui#23]
The Swagger UI [new release](https://github.com/swagger-api/swagger-ui/releases/tag/v4.5.0) includes an [improvement](https://github.com/swagger-api/swagger-ui/pull/7476) to the oauth2RedirectUrl generation. Could you update, please?

**Comment by Deraen** [comment]
Hi, 4.5.0 is now pushed to Clojars.

https://clojars.org/metosin/ring-swagger-ui

**Comment by pedrocicoleme** [comment]
Hi, @Deraen, thanks!
