### ISSUE TITLE
Investigate updating Swagger UI to 5.x

### ISSUE THREAD

**Issue by rome-user** [metosin/ring-swagger-ui#26]
With OpenAPI 3.0 support coming to Reitit in a few weeks, I have decided to experiment with OpenAPI 3.0 with `[metosin/reitit "0.7.0-alpha5"]`. However, it seems that the OpenAPI version declared by reitit is too new for the version of Swagger UI used in this repository. Here is a screenshot.

![openapi](https://github.com/metosin/ring-swagger-ui/assets/114131048/8aec0f6e-aa55-4815-bc83-3aa7c4bde86a)

**Comment by marton-cf** [comment]
You need to include the latest version `[metosin/ring-swager-ui "v5.0.0-alpha.0"]` in your deps. https://github.com/metosin/reitit/blob/master/doc/ring/openapi.md#swagger-ui

**Comment by marton-cf** [comment]
FYI I just opened #27

**Comment by Deraen** [comment]
v5.9.0 is released and some reitit examples are now using that.
