### ISSUE TITLE
API docs generation for multiple defapi declarations

### ISSUE THREAD

**Issue by yogthos** [metosin/ring-swagger-ui#4]
When creating multiple route groups, e.g:

```clojure
(defapi service-routes
  (ring.swagger.ui/swagger-ui
   "/swagger-ui")
  ...)

(defapi restricted-service-routes
  (ring.swagger.ui/swagger-ui
   "/swagger-ui-restricted")
  ...)
```

The `/swagger-ui-restricted` ends up serving the page generated by the first.

**Comment by Deraen** [comment]
The problem is probably in Compojure-api. This project only holds the static files.

Also, all the data in UI is retrieved from `swagger.json` generated by `swagger-docs` route. `swagger-docs` retrieves the api data from request map, which is populated by api-middleware. Because of how middlewares work, if you combine multiple defapi route trees, it's probably that the only one api-middleware will take effect.

**Comment by ikitommi** [comment]
api-middleware shouldn't & can't IMO effect any other branch as request-map is immutable.

**Comment by Deraen** [comment]
````
(defroutes x
  service-routes
  restricted-service-routes)
```

Middlewares of service-routes will be applied even if service-routes doesn't match to the route?

**Comment by Deraen** [comment]
Tested this myself and works fine. Please note that you have to manually configure swagger-json path for both swagger-ui and swagger-docs routes:

```clj
(defapi app2
  (swagger-ui "/docs-b"
    :swagger-docs "/swagger-b.json")
  (swagger-docs "/swagger-b.json")
  ...)
```

`swagger-ui` route doesn't have anyway to know what docs you want to see, so it by default loads the "/swagger.json". `swagger-docs` generates the data and by default will answer to requests to "/swagger.json", if you want to have multiple swagger docs you have to use different routes for them.

**Comment by yogthos** [comment]
Ah that works, I think we can close this then. Probably worth updating the docs to mention it. ;)

**Comment by Deraen** [comment]
Docstrings already document the options. But yeah, better docs wouldn't hurt but README is already so immense I'm hesitant to add stuff to it. I added this to https://github.com/metosin/compojure-api/issues/41 so that we can document this when we have better place for docs.

**Comment by yogthos** [comment]
Sounds good. :)
